language:generic

services:
  -docker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: "my-first-app"
  env: "Myfirstapp-env"

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  bucket_name: "my-first-app-varun"
  bucket_path: "docker"
  on:
    branch: main